In [1]:
import numpy as np

In [6]:
#array slicing 
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr[0])
print(arr[1])

[1 2 3]
[4 5 6]


In [11]:
#range of row 
print(arr[0:2:1]) #start->inclusive:stop->exclusive:step
print(arr[0:3:2])

#reverse indexing 
print(arr[::-1])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [16]:
#range of column
print(arr[:,0:1])
print(" ")
print(arr[1:3,0:1])

[[1]
 [4]
 [7]]
 
[[4]
 [7]]
