In [7]:
#broadcasting - the numpy generates rows and column 
import numpy as np
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr2 = np.array([1,2,3]) #arr1(3,3) arr2(1,3) -> the row and column should be either equal or 1
arr3 = np.array([1,2]) #arr3(1,2) -> column not equal error
print(arr1*arr2) #the matrix multiplication is not applicable each row and column are multiplied 

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [8]:
print(arr1*arr3)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 