In [2]:
import numpy as np

#there are 3 dimensions - 0d 1d 2d 3d and more 
#0d 
arr = np.array(1)
print(arr.ndim)

0


In [5]:
#1d array 
arr = np.array([1,2,3,4,5])
print(arr.ndim)

1


In [6]:
#2d array 
arr = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6]
])
print(arr.ndim)

2


In [7]:
#3d array 
arr = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])
print(arr.ndim)

3


In [11]:
#accessing each dim 

print(arr[0][1][2])
print(arr[0,1,2]) #-> layer,row,column

6
6


In [15]:
#in 3d every layer should have equal rows and columns 
arr = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5] #->error
    ]
])
print(arr.ndim)

3


In [21]:
#reshaping an array
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
arr.reshape(5,2) #total - 10 -> 5*2 = 10

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
#auto shape 
arr.reshape(5,-1)
arr.reshape(5,-1,-1) #cannot auto declare more than one dimension

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])